
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightASIGNARrightDISTINTOSELECT INSERT DELETE UPDATE VALUES FROM WHERE SET INTO JOIN ON ID INTEGER DOUBLE CADENA FECHA BOOL ASIGNAR OP_A_S OP_A_C OP_L NOT OP_R DISTINTO TIPO_JOIN OP_M TODO PUNTOCOMA PUNTO COMA PARENTESISP : S PUNTOCOMAP : S PUNTOCOMA PS : SELECT A FROM T BS : DELETE FROM T BpS : UPDATE T SET N WS : INSERT INTO T PARENTESIS Ap PARENTESIS VALUES YA : TODOA : ApA : MAp : T PUNTO TAp : T PUNTO T COMA ApM : OP_M PARENTESIS Mp PARENTESISMp : TODOMp : T PUNTO TT : IDB : BpB : J T ON EBp : WBp : emptyW : WHERE CC : NOT PARENTESIS F PARENTESISC : FF : FpF : Fp OP_L FFp : T PUNTO T R VR : OP_RR : DISTINTOV : QV : CADENAV : FECHAV : BOOLQ : INTEGERQ : DOUBLEQ : INTEGER U QQ : DOUBLE U QU : OP_A_SU : OP_A_CJ : Jp JOINJp : TIPO_JOINE : T PUNTO T OP_R T PUNTO TN : T PUNTO T ASIGNAR VN : T PUNTO T ASIGNAR V COMA NVp : VVp : V COMA VpY : PARENTESIS Vp PARENTESISY : PARENTESIS Vp PARENTESIS COMA Yempty :'
    
_lr_action_items = {'SELECT':([0,7,],[3,3,]),'DELETE':([0,7,],[4,4,]),'UPDATE':([0,7,],[5,5,]),'INSERT':([0,7,],[6,6,]),'$end':([1,7,18,],[0,-1,-2,]),'PUNTOCOMA':([2,14,22,25,30,31,32,37,38,45,47,48,51,64,69,70,75,76,77,78,79,80,82,84,94,95,96,102,104,],[7,-15,-47,-47,-4,-18,-19,-3,-16,-20,-22,-23,-5,-24,-17,-21,-28,-29,-30,-31,-32,-33,-6,-25,-34,-35,-45,-46,-40,]),'TODO':([3,21,],[10,28,]),'OP_M':([3,],[13,]),'ID':([3,5,15,17,19,20,21,23,33,36,39,42,44,50,54,57,58,59,62,83,85,98,103,],[14,14,14,14,14,14,14,14,14,14,14,14,14,14,-38,14,14,14,14,14,14,14,14,]),'FROM':([4,8,10,11,12,14,26,43,55,],[15,19,-7,-8,-9,-15,-10,-12,-11,]),'INTO':([6,],[17,]),'PUNTO':([9,14,29,34,49,68,101,],[20,-15,44,50,59,83,103,]),'PARENTESIS':([13,14,24,26,27,28,46,48,52,55,56,63,64,67,75,76,77,78,79,80,84,90,91,94,95,99,100,],[21,-15,36,-10,43,-13,57,-23,61,-11,-14,70,-24,81,-28,-29,-30,-31,-32,-33,-25,96,-43,-34,-35,81,-44,]),'SET':([14,16,],[-15,23,]),'WHERE':([14,22,25,35,74,75,76,77,78,79,80,93,94,95,],[-15,33,33,33,-41,-28,-29,-30,-31,-32,-33,-42,-34,-35,]),'TIPO_JOIN':([14,25,],[-15,41,]),'COMA':([14,26,74,75,76,77,78,79,80,91,94,95,96,],[-15,42,85,-28,-29,-30,-31,-32,-33,97,-34,-35,99,]),'ON':([14,53,],[-15,62,]),'ASIGNAR':([14,60,],[-15,66,]),'OP_R':([14,65,92,],[-15,72,98,]),'DISTINTO':([14,65,],[-15,73,]),'NOT':([33,],[46,]),'JOIN':([40,41,],[54,-39,]),'OP_L':([48,75,76,77,78,79,80,84,94,95,],[58,-28,-29,-30,-31,-32,-33,-25,-34,-35,]),'VALUES':([61,],[67,]),'CADENA':([66,71,72,73,81,97,],[76,76,-26,-27,76,76,]),'FECHA':([66,71,72,73,81,97,],[77,77,-26,-27,77,77,]),'BOOL':([66,71,72,73,81,97,],[78,78,-26,-27,78,78,]),'INTEGER':([66,71,72,73,81,86,87,88,89,97,],[79,79,-26,-27,79,79,-36,-37,79,79,]),'DOUBLE':([66,71,72,73,81,86,87,88,89,97,],[80,80,-26,-27,80,80,-36,-37,80,80,]),'OP_A_S':([79,80,],[87,87,]),'OP_A_C':([79,80,],[88,88,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'P':([0,7,],[1,18,]),'S':([0,7,],[2,2,]),'A':([3,],[8,]),'T':([3,5,15,17,19,20,21,23,33,36,39,42,44,50,57,58,59,62,83,85,98,103,],[9,16,22,24,25,26,29,34,49,9,53,9,56,60,49,49,65,68,92,34,101,104,]),'Ap':([3,36,42,],[11,52,55,]),'M':([3,],[12,]),'Mp':([21,],[27,]),'Bp':([22,25,],[30,38,]),'W':([22,25,35,],[31,31,51,]),'empty':([22,25,],[32,32,]),'N':([23,85,],[35,93,]),'B':([25,],[37,]),'J':([25,],[39,]),'Jp':([25,],[40,]),'C':([33,],[45,]),'F':([33,57,58,],[47,63,64,]),'Fp':([33,57,58,],[48,48,48,]),'E':([62,],[69,]),'R':([65,],[71,]),'V':([66,71,81,97,],[74,84,91,91,]),'Q':([66,71,81,86,89,97,],[75,75,75,94,95,75,]),'Y':([67,99,],[82,102,]),'U':([79,80,],[86,89,]),'Vp':([81,97,],[90,100,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> P","S'",1,None,None,None),
  ('P -> S PUNTOCOMA','P',2,'p_P1','aselect.py',15),
  ('P -> S PUNTOCOMA P','P',3,'p_P2','aselect.py',18),
  ('S -> SELECT A FROM T B','S',5,'p_S1','aselect.py',22),
  ('S -> DELETE FROM T Bp','S',4,'p_S2','aselect.py',25),
  ('S -> UPDATE T SET N W','S',5,'p_S3','aselect.py',28),
  ('S -> INSERT INTO T PARENTESIS Ap PARENTESIS VALUES Y','S',8,'p_S4','aselect.py',31),
  ('A -> TODO','A',1,'p_A1','aselect.py',35),
  ('A -> Ap','A',1,'p_A2','aselect.py',38),
  ('A -> M','A',1,'p_A3','aselect.py',41),
  ('Ap -> T PUNTO T','Ap',3,'p_Ap1','aselect.py',45),
  ('Ap -> T PUNTO T COMA Ap','Ap',5,'p_Ap2','aselect.py',48),
  ('M -> OP_M PARENTESIS Mp PARENTESIS','M',4,'p_M','aselect.py',53),
  ('Mp -> TODO','Mp',1,'p_Mp1','aselect.py',57),
  ('Mp -> T PUNTO T','Mp',3,'p_Mp2','aselect.py',60),
  ('T -> ID','T',1,'p_T','aselect.py',65),
  ('B -> Bp','B',1,'p_B1','aselect.py',69),
  ('B -> J T ON E','B',4,'p_B2','aselect.py',72),
  ('Bp -> W','Bp',1,'p_Bp1','aselect.py',76),
  ('Bp -> empty','Bp',1,'p_BpEmpty','aselect.py',79),
  ('W -> WHERE C','W',2,'p_W','aselect.py',83),
  ('C -> NOT PARENTESIS F PARENTESIS','C',4,'p_C1','aselect.py',87),
  ('C -> F','C',1,'p_C2','aselect.py',90),
  ('F -> Fp','F',1,'p_F1','aselect.py',94),
  ('F -> Fp OP_L F','F',3,'p_F2','aselect.py',97),
  ('Fp -> T PUNTO T R V','Fp',5,'p_Fp','aselect.py',101),
  ('R -> OP_R','R',1,'p_R1','aselect.py',105),
  ('R -> DISTINTO','R',1,'p_R2','aselect.py',108),
  ('V -> Q','V',1,'p_V1','aselect.py',112),
  ('V -> CADENA','V',1,'p_V2','aselect.py',115),
  ('V -> FECHA','V',1,'p_V3','aselect.py',118),
  ('V -> BOOL','V',1,'p_V4','aselect.py',121),
  ('Q -> INTEGER','Q',1,'p_Q1','aselect.py',126),
  ('Q -> DOUBLE','Q',1,'p_Q2','aselect.py',129),
  ('Q -> INTEGER U Q','Q',3,'p_Q3','aselect.py',132),
  ('Q -> DOUBLE U Q','Q',3,'p_Q4','aselect.py',135),
  ('U -> OP_A_S','U',1,'p_U1','aselect.py',139),
  ('U -> OP_A_C','U',1,'p_U2','aselect.py',142),
  ('J -> Jp JOIN','J',2,'p_J','aselect.py',146),
  ('Jp -> TIPO_JOIN','Jp',1,'p_Jp','aselect.py',150),
  ('E -> T PUNTO T OP_R T PUNTO T','E',7,'p_E','aselect.py',154),
  ('N -> T PUNTO T ASIGNAR V','N',5,'p_N1','aselect.py',158),
  ('N -> T PUNTO T ASIGNAR V COMA N','N',7,'p_N2','aselect.py',161),
  ('Vp -> V','Vp',1,'p_Vp1','aselect.py',165),
  ('Vp -> V COMA Vp','Vp',3,'p_Vp2','aselect.py',168),
  ('Y -> PARENTESIS Vp PARENTESIS','Y',3,'p_Y1','aselect.py',171),
  ('Y -> PARENTESIS Vp PARENTESIS COMA Y','Y',5,'p_Y2','aselect.py',175),
  ('empty -> <empty>','empty',0,'p_empty','aselect.py',179),
]
